<a href="https://colab.research.google.com/github/sangavivp/ML-AI-Practice/blob/main/PandasANDNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 7)], dtype=float)
c = np.array([(1.5, 3, 4), (2, 5.5, 3), (7, 7.5, 4)], dtype=float)

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1., 2., 3.],
       [4., 5., 7.]])

In [5]:
c

array([[1.5, 3. , 4. ],
       [2. , 5.5, 3. ],
       [7. , 7.5, 4. ]])

In [6]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
d = np.arange(10, 25, 5) # Creating within a range in the array with step size as the parameter
d

array([10, 15, 20])

In [9]:
np.linspace(0, 2, 9) # Creates evenly spaced 9 numbers


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.full((2, 2), 7) # Constant array

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(2) # Indentity matrix

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2, 2)) # array with Random values

array([[0.90375947, 0.87630353],
       [0.57133425, 0.24227376]])

In [13]:
np.empty((3, 2)) # empty array

array([[1., 2.],
       [3., 4.],
       [5., 7.]])

In [14]:
np.save('my_array', a)