<a href="https://colab.research.google.com/github/sangavivp/ML-AI-Practice/blob/main/PandasANDNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 7)], dtype=float)
c = np.array([(1.5, 3, 4), (2, 5.5, 3), (7, 7.5, 4)], dtype=float)

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1., 2., 3.],
       [4., 5., 7.]])

In [5]:
c

array([[1.5, 3. , 4. ],
       [2. , 5.5, 3. ],
       [7. , 7.5, 4. ]])

In [6]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
d = np.arange(10, 25, 5) # Creating within a range in the array with step size as the parameter
d

array([10, 15, 20])

In [9]:
np.linspace(0, 2, 9) # Creates evenly spaced 9 numbers


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.full((2, 2), 7) # Constant array

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(2) # Indentity matrix

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2, 2)) # array with Random values

array([[0.46692423, 0.48877523],
       [0.02000997, 0.06327376]])

In [13]:
np.empty((3, 2)) # empty array

array([[1., 2.],
       [3., 4.],
       [5., 7.]])

In [14]:
np.save('my_array', a)

In [15]:
#Inspecting an array
a = np.array([1, 2, 3, 4])
a.shape

(4,)

In [16]:
len(a)

4

In [17]:
a.ndim

1

In [18]:
a.size

4

In [19]:
a.dtype

dtype('int64')

In [20]:
a.dtype.name

'int64'

In [21]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [23]:
b = np.array(([2, 3, 4], [5, 6, 7]))

In [24]:
a-b # broadcasting issue as its of incompatible sizes

ValueError: ignored

In [25]:
b = np.array(([2, 3, 4, 5], [5, 6, 7, 8]))
a-b

array([[-1, -1, -1, -1],
       [-4, -4, -4, -4]])

In [26]:
a==b

array([[False, False, False, False],
       [False, False, False, False]])

In [27]:
a<2

array([ True, False, False, False])

In [28]:
a.sum()

10

In [29]:
a.min()

1

In [30]:
# numpy array is an instance of ndarray - https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy

In [32]:
c = np.array(([1, 2, 3, 4], [0, 3, 4, 5]))
c.max(axis=0) # column wise among the rows

array([1, 3, 4, 5])

In [34]:
c = np.array(([1, 2, 3, 4], [0, 3, 10, 5]))
c.max(axis=1) # row wise along the columns - highest in each row

array([ 4, 10])

In [37]:
k = c.cumsum(axis=1)
k

array([[ 1,  3,  6, 10],
       [ 0,  3, 13, 18]])

In [38]:
l = c.view() # array with the same data it the reference is retained

In [41]:
l[1][1] = 10
l

array([[ 1,  2,  3,  4],
       [ 0, 10, 10,  5]])

In [42]:
c

array([[ 1,  2,  3,  4],
       [ 0, 10, 10,  5]])

In [44]:
cp = np.copy(c) # uncoupled copy

In [46]:
cp[1][1] = 5
cp

array([[ 1,  2,  3,  4],
       [ 0,  5, 10,  5]])

In [47]:
c

array([[ 1,  2,  3,  4],
       [ 0, 10, 10,  5]])

In [48]:
cp2 = c.copy() # uncoupled copy

In [49]:
cp2[1][1] = 8
cp2

array([[ 1,  2,  3,  4],
       [ 0,  8, 10,  5]])

In [50]:
c

array([[ 1,  2,  3,  4],
       [ 0, 10, 10,  5]])